// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbEuLBXmsn6LIoZNuQ0zLIsMIoH8nVYz8',
    appId: '1:880154669907:web:3f963fc2abbdccd0f8a7a6',
    messagingSenderId: '880154669907',
    projectId: 'chok-e-chat',
    authDomain: 'chok-e-chat.firebaseapp.com',
    storageBucket: 'chok-e-chat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKdXywZz9MoJ4ZHgvGyBphHHDGJ9WQTuw',
    appId: '1:880154669907:android:569d9608f6062080f8a7a6',
    messagingSenderId: '880154669907',
    projectId: 'chok-e-chat',
    storageBucket: 'chok-e-chat.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbEuLBXmsn6LIoZNuQ0zLIsMIoH8nVYz8',
    appId: '1:880154669907:web:832839f4472a11bef8a7a6',
    messagingSenderId: '880154669907',
    projectId: 'chok-e-chat',
    authDomain: 'chok-e-chat.firebaseapp.com',
    storageBucket: 'chok-e-chat.firebasestorage.app',
  );

}